---
title: "DS_Assignment4_20180215"
author: "Ian Lee"
date: "February 15, 2018"
output:
  html_document:
    df_print: paged
---

#DS assignment 4 commands used 
```{r}
#Load all these in as well please
library(tidyverse)
library(phyloseq)
metadata = read.table(file="Saanich.metadata.txt", header=TRUE, row.names=1, sep="\t")
load("phyloseq_object.RData")
physeq_percent = transform_sample_counts(physeq, function(x) 100 * x/sum(x))

source("https://bioconductor.org/biocLite.R")

biocLite("phyloseq")

library(phyloseq)
#loading the phyloseq data
load("phyloseq_object.RData")

#dot plots
ggplot(metadata, aes(x=O2_uM, y=Depth_m))

ggplot(metadata, aes(x=O2_uM, y=Depth_m)) +
  geom_point()
#equivalent to 
ggplot(metadata) +
  geom_point(aes(x=O2_uM, y=Depth_m))

#how to change colour or size of plot 
ggplot(metadata, aes(x=O2_uM, y=Depth_m, color="blue")) +
  geom_point()#this is not right as gg plot cannot target the specific points this way
#this is correct
ggplot(metadata, aes(x=O2_uM, y=Depth_m)) +
  geom_point(color="blue")  
#changing the shapes to square
ggplot(metadata, aes(x=O2_uM, y=Depth_m)) +
  geom_point(shape="square")
#changing the size of the plot dots
ggplot(metadata, aes(x=O2_uM, y=Depth_m)) +
  geom_point(size=10)#thats really big btw
#where size equals to an actual variable
ggplot(metadata, aes(x=O2_uM, y=Depth_m, size=OxygenSBE_V)) +
  geom_point()


#Excercise 1
ggplot(metadata, aes(x=NO2_uM, y=Depth_m)) +
  geom_point(color="purple", shape=17)  #17= triangle
#guide to shapes http://sape.inf.usi.ch/sites/default/files/ggplot2-shape-identity.png
#shift click to follow link


#Excersise 2
metadata %>%
  select(matches("Temp"))

metadata %>% 
  mutate(Temperature_F = Temperature_C*1.8+32) %>% 
  ggplot(aes(x=Temperature_F, y=Depth_m)) + 
  geom_point()


physeq
#something about how convenient phyloseq is because it plays well with the program. 
#by doing the next step we can plot a bar graph according to phylum level of communities
plot_bar(physeq, fill="Phylum")

#Phyloseq's transform_sample_counts function is used for a common problem, which is to mutate OTU table values into percentages of total 
physeq_percent = transform_sample_counts(physeq, function(x) 100 * x/sum(x))

#now we can plot it accordingly
plot_bar(physeq_percent, fill="Phylum")

#the next thing we're gonna do is to merge all portions of bars that are the same colour together
plot_bar(physeq_percent, fill="Phylum") + 
  geom_bar(aes(fill=Phylum), stat="identity")

#Exercise 3
plot_bar(physeq, fill="Family")
plot_bar(physeq_percent, fill="Class")
#plotting class cause its easier but filling in the blacks too
#Filling in the labels
plot_bar(physeq_percent, fill="Class") + 
  geom_bar(aes(fill=Class), stat="identity")+
  ggtitle("Classes from 10 to 200m in the Saanich inlet")+
  xlab("Sample Depth")+
  ylab("Percent Relative Abundance")

#Faceting can be done with the following:
plot_bar(physeq_percent, fill="Phylum") +
  geom_bar(aes(fill=Phylum), stat="identity") +
  facet_wrap(~Phylum)
#The scales for each graph can be adjusted to fit each category so that we can visualize relative values
#We can also remove the legend since it is not relevant
plot_bar(physeq_percent, fill="Phylum") +
  geom_bar(aes(fill=Phylum), stat="identity") +
  facet_wrap(~Phylum, scales="free_y") +
  theme(legend.position="none")

#Exercise 4

#so it says to use gather to allow for manipulation of the data
metadata %>%
  gather("O2_uM,PO4_uM,SiO2_uM,NO3_uM,NH4_uM,NO2_uM")

#first we're gonna remade a simple ggplot with Depth as X axis and O2 as y axis
ggplot(metadata, aes(x=Depth_m, y=O2_uM)) +
  geom_point()+
  geom_line()

#This works for only 1 nutrient. We will thus create multiple designations for each nutrient type 

#gather allows you to group all the nutrients under a new column called Nutrients_uM, with units in uM
metadata %>% 
  gather(Nutrients_uM, uM, NH4_uM, NO2_uM, NO3_uM, O2_uM, PO4_uM, SiO2_uM) %>%
  ggplot() +geom_point(aes(x=Depth_m, y=uM)) + geom_line(aes(x=Depth_m, y=uM)) +
  facet_wrap(~Nutrients_uM, scales="free_y")
